// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7du27Xr_Lpdkc24UDl8BA_PjWch_zkpM',
    appId: '1:1005934735625:web:0e7f4b9621b7ac0770a3d8',
    messagingSenderId: '1005934735625',
    projectId: 'prepmaster-tedy21',
    authDomain: 'prepmaster-tedy21.firebaseapp.com',
    storageBucket: 'prepmaster-tedy21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD-PVv7XdX03SchjfRVc3uChu1hCJrle4',
    appId: '1:1005934735625:android:e0721278175757d570a3d8',
    messagingSenderId: '1005934735625',
    projectId: 'prepmaster-tedy21',
    storageBucket: 'prepmaster-tedy21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgXHTuQk7PPj2X_kpuGyIccRGx6eKKwo4',
    appId: '1:1005934735625:ios:db8dfc6ae1f5a9c270a3d8',
    messagingSenderId: '1005934735625',
    projectId: 'prepmaster-tedy21',
    storageBucket: 'prepmaster-tedy21.firebasestorage.app',
    iosBundleId: 'com.prepmaster.prepMaster',
  );
}
